name: Deploy on Main

on: 
  push:
    branches:
      - '**'


jobs:
  deploy:
    runs-on: self-hosted


    steps:
      - uses: actions/checkout@v3
        with:
          repository: ktg69/Workflow_test.git
          ref: main
      - run: cd ..
             terraform init   
